

import Foundation

class MyFriendsViewModel {
    let users: [User] = [
        User(name: "Ulan Seitkali",
             imageName: "Seitkali",
             position: String(localized: "Business magnate"),
             status: .online,
             nickName: "Ulala",
             numberOfFriends: 10048,
             isYourFriend: true),
        User(name: "Mark Zuckerberg",
             imageName: "Zuckerberg",
             position: String(localized: "Software Engineer"),
             status: .recent,
             nickName: "Mark",
             numberOfFriends: 1390,
             isYourFriend: true),
        User(name: "Larry Page",
             imageName: "Page",
             position: String(localized: "CEO"),
             status: .recent,
             nickName: "Larry",
             numberOfFriends: 768,
             isYourFriend: true),
        User(name: "Barack Obama",
             imageName: "Obama",
             position: String(localized: "Ex-President"),
             status: .offline,
             nickName: "Baraka",
             numberOfFriends: 9001,
             isYourFriend: true),
        User(name: "Elon Musk",
             imageName: "Musk",
             position: String(localized: "Engineer"),
             status: .online,
             nickName: "Muskular",
             numberOfFriends: 978,
             isYourFriend: true),
        User(name: "Steve Jobs",
             imageName: "Jobs",
             position: String(localized: "Entrepreneur"),
             status: .offline,
             nickName: "Steve",
             numberOfFriends: 567,
             isYourFriend: true),
        User(name: "Tim Cook",
             imageName: "Cook",
             position: String(localized: "CEO"),
             status: .offline,
             nickName: "Tim",
             numberOfFriends: 231,
             isYourFriend: true),
        User(name: "Warren Buffett",
             imageName: "Buffett",
             position: String(localized: "Investor"),
             status: .recent,
             nickName: "Buffet's",
             numberOfFriends: 12312,
             isYourFriend: true),
        User(name: "Sergey Brin",
             imageName: "Brin",
             position: String(localized: "Entrepreneur"),
             status: .online,
             nickName: "Nil",
             numberOfFriends: 1202,
             isYourFriend: true),
        User(name: "Jeff Bezos",
             imageName: "Bezos",
             position: String(localized: "Entrepreneur"),
             status: .online,
             nickName: "Bezos",
             numberOfFriends: 134,
             isYourFriend: true)
    ]
}

